# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update and group npm dependencies in the client directory
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"

  # Update and group Python dependencies in the server directory
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"

  # Update and group Docker images used in Dockerfiles and docker-compose files at the repo root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
