# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update and group npm dependencies in the client directory
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    group: "client-deps"

  # Update and group Python dependencies in the server directory
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    group: "server-deps"

  # Update and group Docker images used in Dockerfiles and docker-compose files at the repo root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    group: "docker-deps"

update_groups:
  client-deps:
    # The pattern "*" means all npm dependencies will be bundled together.
    patterns:
      - "*"
  server-deps:
    # All pip dependencies in the server group are included.
    patterns:
      - "*"
  docker-deps:
    # All docker-related dependency updates will be grouped.
    patterns:
      - "*"
