# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update npm dependencies in the client folder
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Update Python dependencies listed in server/requirements.txt
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"

  # Update Docker images used in your Dockerfiles (Dockerfile.client and Dockerfile.server)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
