FROM --platform=linux/amd64 public.ecr.aws/docker/library/python:3.11
WORKDIR /app

RUN mkdir ./api
COPY server ./api
RUN pip install --upgrade pip
RUN pip install -r ./api/requirements.txt
ENV PYTHON_ENV=production

EXPOSE 8000 8001 8002 
WORKDIR /app/api
