services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    environment:
      - PYTHON_ENV=development
    volumes:
      - ./server:/app/api
    command: >
      sh -c "WORKER_ID=1 python3 -m sanic api.app --host 0.0.0.0 --port 8000 --workers 1 & 
      WORKER_ID=2 python3 -m sanic api.app --host 0.0.0.0 --port 8001 --workers 1 & 
      WORKER_ID=3 python3 -m sanic api.app --host 0.0.0.0 --port 8002 --workers 1 & 
      wait"
    
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000:80
    depends_on:
      - backend
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    command: >
      sh -c "nginx -g 'daemon off;'"

