services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    environment:
      - PYTHON_ENV=development
    volumes:
      - ./server:/app/api
    
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000:80
    depends_on:
      - backend
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf

