name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: client
      - name: Install Dependencies
        run: npm ci
        working-directory: client
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm start
          wait-on: "http://localhost:5173"
          record: true
          parallel: true 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
