name: Run Tests (Frontend)

on: [push]

jobs:
  vite-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build front-end files
        run: npm run build

      - name: Run tests
        run: npm test
