name: Run Tests (Backend)

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install server dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          # install pylint or pytest explicitly
          pip install pylint pytest

      - name: Lint with pylint
        working-directory: server
        run: |
          # will exit non-zero if there are lint errors
          pylint --rcfile=.pylintrc .

      - name: Run pytest
        working-directory: server
        run: |
          pytest tests --maxfail=1 --disable-warnings -q
